### ISSUE TITLE
enhancement: wow slider

### ISSUE THREAD

**Issue by propertunist** [iionly/Elgg_1.8_tidypics#1]
while i'm throwing around enhancement ideas.. i thought i'd draw your attention here:

http://wowslider.com/demo.html

i'm imagining you are already aware of this code slideshow solution.. it would be great with tidypics. :)

edit: i just noticed that wow slider now only appears to function via a downloadable exe and direct php use appears to be not so much used.. not sure why that is.

**Comment by propertunist** [comment]
i just found a slideshow plugin for jquery here on git hub that looks awesome:

https://github.com/joelambert/Flux-Slider

http://blog.joelambert.co.uk/2011/05/05/flux-slider-css3-animation-based-image-transitions/

**Comment by iionly** [comment]
Replacing the PicslensLite slideshow is on my agenda for sure. If I find the time, I will deal with it. I have some ideas already what slideshow script to use but will keep your suggestions in mind nonetheless.

Closing for now.
