### ISSUE TITLE
enhancement: batch resize all thumbnails

### ISSUE THREAD

**Issue by propertunist** [iionly/Elgg_1.8_tidypics#2]
one feature that is missing (as far as i know) from tidypics is the ability to auto-batch process the images to create new thumbnail files where the thumbnail size is changed in the admin settings. the manual thumbnail generator tool is impractical for more than a small amount of images.. so, presently, if we change the size of the thumbnails, perhaps due to re-designing the theme / layout of the installation.. we are stuck with either having a mixture of image sizes or having to somehow manually process each image.

maybe elggbatch can be used in combination with a cron event to schedule batch conversions.. not a simple task perhaps.... i'm not sure though as i haven't gotten elgg batch to function in my own code yet.

**Comment by iionly** [comment]
Re-sizing of all thumbnails option added with https://github.com/iionly/Elgg_1.8_tidypics/commit/951ffff58a9421e2597c347d7e67d67102e0d902. This commit will be part of the next release 1.8.5 of Tidypics.
