### ISSUE TITLE
optimise thumbnail.php

### ISSUE THREAD

**Issue by propertunist** [iionly/Elgg_1.8_tidypics#4]
i recently have been optimising my site using newrelic's online analysis system.
while doing that i saw that the videolist  thumbnail process was taking 2000ms+ instead of 20ms.. 
this was because the thumbnail.php page was being rendered as a unique page and loading the entire elgg engine for each thumbnail! obviously this is inefficient.
i rewrote the thumbnail script for videolist to match the method used in the profile plugin and now the time is around 20ms on my site and the page load is decreased by 3-5 SECONDS! lol

i notice that tidypics uses the same inefficient process for accessing thumbnails.. so could also be rewritten in this way. the change is to alter the icon_url_override in the start.php file and also the way the thumbnail.php file operates.

i can post the code here if you are wanting to do this?

**Comment by propertunist** [comment]
ah so looking through the tidypics code i see that the way the thumbnail.php file is coded and used is different to videolist. 
so to implement this efficiency change would require removing thumbnail.php from the pagehandler code in start.php and possibly utilising an icon over-ride hook in the way that videolist does.

**Comment by iionly** [comment]
If you think it would be worth modifying to increase performance I'm interested in what you come up with. I don't know what you changed in the videolist plugin to improve it, so I can't say if it would be worth the effort for Tidypics, too. If you modify it please also keep in mind that Tidypics uses it's own image sizes, so it might not be possible to use Elgg core functions only. I can't say right now how and where thumbnail.php is used exactly and what might be the best way to change it. But if you want to make a pull request, please do.

**Comment by propertunist** [comment]
this approach is certainly a worthwhile change to all plugins that use thumbnails (including file plugin i think).
in videolist i copied the format that is already used in the profile plugin for avatars, which is to do a direct call to the database from the thumbnail.php file and not load the entire engine. loading the entire engine more than once per 'actual' html page is not necessary - yet all thumbnail type pages have been coded to do this (except profile avatars).
my list of tasks is continually growing presently. so i don't know when i will get to looking at tidypics.. possibly in the next few weeks.

**Comment by iionly** [comment]
okay. I will wait. :)

**Comment by propertunist** [comment]
on closer inspection of tidypics i see that most likely the way that classes are being used is overcoming the issue that was present with videolist.. so there's no potential performance improvement using the method i used with videolist..
for some reason the tidypics thumbnails continue to load very slowly on my site..
this would be improved if the tidypics thumbnails (and other full size images) had their file extension added in elgg since then my cdn could cache them (cloudflare.com) - since they base which files to cache on the file extension and the tidypics files presently have no file extension.
there is another issue though because the videolist icons do not have extensions, are larger files and are loading much quicker than tidypics presently for me..  i continue!

**Comment by iionly** [comment]
I don't have any experience with cloudflare or any other cdn solutions. Tidypics' thumbnail.php includes some (client side) caching code. As I understand it icondirect.php also includes some caching mechanisms. Maybe it's worth investigation to bring the code used in icondirect.php into thumbnail.php. Though I can't say without testing this out if it would make any sense.

**Comment by iionly** [comment]
Closing as I don't see any relevance for Tidypics at the moment.

**Comment by propertunist** [comment]
i am currently dealing with this same issue for an on-server video plugin i am making here, so will look again at this with tidypics now that i have more experience
